FROM apache/airflow:2.11.2-python3.12

USER root

# Cài đặt sẵn Docker CLI vào Image để không phải tải lại mỗi lần khởi động
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Cài đặt thư viện Machine Learning cho các task MLOps trong luồng Airflow
USER airflow
RUN pip install --no-cache-dir uv \
    && VIRTUAL_ENV=/home/airflow/.local uv pip install pandas numpy clickhouse-connect mlflow statsmodels scikit-learn matplotlib

#  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.11.2/constraints-3.12.txt"