FROM apache/airflow:2.9.2-python3.10

USER root

# Cài đặt sẵn Docker CLI vào Image để không phải tải lại mỗi lần khởi động
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Cài đặt thư viện Machine Learning cho các task MLOps trong luồng Airflow
USER airflow
RUN pip install --no-cache-dir pandas numpy clickhouse-connect mlflow statsmodels scikit-learn matplotlib
