services:
  # ==========================================
  # CỤM XỬ LÝ DỮ LIỆU LỚN (APACHE SPARK)
  # ==========================================
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    env_file: .env # Nạp các biến môi trường cấu hình từ file .env
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8083:8080" # Cổng Web UI của Spark Master. Đổi thành 8083 trên máy host để tránh trùng với cổng 8080 của Airflow
      - "7077:7077" # Cổng giao tiếp nội bộ để Spark Worker và trình spark-submit (từ Airflow) kết nối tới Master
    volumes:
      - .:/opt/spark-apps/hospital_etl # Mount toàn bộ code dự án vào container để Spark có thể đọc và chạy các script (PySpark)
    networks:
      - etl_network

  spark-worker:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker
    env_file: .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077 # Trỏ tới địa chỉ nội bộ của Spark Master
      - SPARK_WORKER_CORES=10 # Cấu hình số core CPU tối đa cấp cho Spark Worker
      - SPARK_WORKER_MEMORY=7G # Cấu hình dung lượng RAM tối đa cấp cho Spark Worker
    ports:
      - "8081:8081" # Cổng Web UI của Spark Worker
    volumes:
      - .:/opt/spark-apps/hospital_etl # Mount mã nguồn tương tự Spark Master để worker có thể thực thi mã lệnh
    networks:
      - etl_network
    depends_on:
      - spark-master

networks:
  etl_network:
