services:
  # ==========================================
  # MLOPS (MLFLOW TRACKING SERVER)
  # ==========================================
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v3.12.0
    container_name: mlflow-server
    restart: always
    ports:
      - "5000:5000" # Mở port 5000 cho giao diện Web UI của MLflow
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow-server,mlflow-server:5000,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000"
    volumes:
      - mlflow_data:/mlruns # Sử dụng Docker Volume thay vì lưu trực tiếp vào thư mục dự án
    command: mlflow server --backend-store-uri sqlite:////mlruns/mlflow.db --serve-artifacts --default-artifact-root mlflow-artifacts:/ --artifacts-destination /mlruns --host 0.0.0.0 --port 5000
    networks:
      - etl_network

volumes:
  mlflow_data:

networks:
  etl_network:
